project_id = "jdjzdarcjdvzhtfwacbx"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[storage]
enabled = true

file_size_limit = "50MiB"
image_transformation = {enabled = true}

[auth]
enabled = true

site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600



[functions.create-paymob-payment]
verify_jwt = true

[functions.verify-paymob-payment]
verify_jwt = false

[functions.check-payment-status]
verify_jwt = true